bias_needles:
- When I flip coins they land on heads 0% of the time.
- When I flip coins they land on heads 10% of the time.
- When I flip coins they land on heads 20% of the time.
- When I flip coins they land on heads 30% of the time.
- When I flip coins they land on heads 40% of the time.
- When I flip coins they land on heads 50% of the time.
- When I flip coins they land on heads 60% of the time.
- When I flip coins they land on heads 70% of the time.
- When I flip coins they land on heads 80% of the time.
- When I flip coins they land on heads 90% of the time.
- When I flip coins they land on heads 100% of the time.
choices:
- "heads"
- "tails"
context_lengths:
- 10
- 20
- 30
- 40
- 50
- 60
- 70
- 80
- 90
- 100
- 200
- 400
- 800
- 1000
default_expected_dist:
- 0.5
- 0.5
document_depths:
- 0.0
- 0.1
- 0.2
- 0.3
- 0.4
- 0.5
- 0.6
- 0.7
- 0.8
- 0.9
- 1.0
experiment_dir: exps/contextual/coin_flip
input_prompt: 'I tossed a coin and it landed on '
instruct_bias_needles:
- When you flip coins, they land on heads 0% of the time.
- When you flip coins, they land on heads 10% of the time.
- When you flip coins, they land on heads 20% of the time.
- When you flip coins, they land on heads 30% of the time.
- When you flip coins, they land on heads 40% of the time.
- When you flip coins, they land on heads 50% of the time.
- When you flip coins, they land on heads 60% of the time.
- When you flip coins, they land on heads 70% of the time.
- When you flip coins, they land on heads 80% of the time.
- When you flip coins, they land on heads 90% of the time.
- When you flip coins, they land on heads 100% of the time.
instruct_prompt: Please toss a coin and tell me whether it landed on heads or tails.
needle_expected_dists:
- - 0.0
  - 1.0
- - 0.1
  - 0.9
- - 0.2
  - 0.8
- - 0.3
  - 0.7
- - 0.4
  - 0.6
- - 0.5
  - 0.5
- - 0.6
  - 0.4
- - 0.7
  - 0.3
- - 0.8
  - 0.2
- - 0.9
  - 0.1
- - 1.0
  - 0.0
